# Generated by Django 3.1.5 on 2021-05-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0003_auto_20210525_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='filename',
            field=models.CharField(default='', max_length=10),
        ),
    ]
