# Generated by Django 3.1.5 on 2021-05-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0004_profile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='filename',
            field=models.CharField(default='', max_length=15),
        ),
    ]
