# Generated by Django 3.1.5 on 2021-05-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0005_auto_20210525_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='strain',
            field=models.CharField(default='', max_length=4),
        ),
    ]
